baseURL = "https://bhktf.github.io/"
languageCode = "en-us"
title = "BHKTF"

theme = "PaperMod"
themesDir = "themes"

[params]
    env = "production"
    title = "BHKTF"
    description = "Official trip portal for Alex, Archie, Joseph, and Stanley."
    defaultTheme = "dark"
    disableThemeToggle = true

    [params.profileMode]
        enabled = false
